### ISSUE TITLE
Create-React-App boilerplate in Readme.md

### ISSUE THREAD

**Issue by siddhant1** [ossn/fixme#115]

**Comment by siddhant1** [comment]
Either we should fix it or we should convert all scripts from npm to yarn

**Comment by ashu8912** [comment]
I think create-react-app boilerplate shouldn't be there..... 
because  boilerplate generated by a cli are generally not added in the docs of a project
moreover we can just mention that this project was bootstrapped with create-react-app and provide
a link to the readme.md 
writing all of the config for create-react-app in our project docs is not a good idea

Make readme as clean as possible

**Comment by siddhant1** [comment]
@alexdor @bacharakis should I do this or do we need the boilerplate?

**Comment by alexdor** [comment]
Feel free to remove it and just keep the link to the newer version, if somebody wants to check it out
