### ISSUE TITLE
Document does not have a meta description

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#18]
Meta descriptions may be included in search results to concisely summarize page content. [Learn more](https://developers.google.com/web/tools/lighthouse/audits/description)

**Comment by yunduz** [comment]
Since there are multiple parts to the fixme app (issues, projects, about), meta description tag should be different for each one. To load different meta description tag for each route we could use [react-helmet](https://www.npmjs.com/package/react-helmet), however, the changes will take effect on the client side, thus, crawlers won't see the correct meta description. It seems that the typical solution that people use is [to render each route on the server](https://alligator.io/react/react-helmet/).

**Comment by Muljayan** [comment]
@yunduz are you working on this ? If not shall i go ahead with it ?

**Comment by Muljayan** [comment]
Hi, I had some time to spare so i addressed this issue in  #43 . Currently the Home, Issues and Projects page have custom document header elements implement.

**Comment by yunduz** [comment]
@Muljayan Sorry for missing the messages and not finishing the task! Thank you for fixing it!

**Comment by Muljayan** [comment]
@yunduz all cool :smile: 
@alexdor please refer PR #45 . 
It is the same as #43 but made it with a sub branch instead of my master branch. Sorry for any inconvenience caused.
