### ISSUE TITLE
Document doesn't use legible font sizes for mobile

### ISSUE THREAD

**Issue by alexdor** [ossn/fixme#26]
88.03% of text is too small.

<img width="672" alt="screen shot 2018-09-27 at 14 36 00" src="https://user-images.githubusercontent.com/8433031/46146320-be4b7580-c262-11e8-8c37-d8318cda2047.png">
<img width="656" alt="screen shot 2018-09-27 at 14 40 21" src="https://user-images.githubusercontent.com/8433031/46146551-56e1f580-c263-11e8-94ef-c55749eb112b.png">

**Comment by tabshaikh** [comment]
.issues-container .issue-card-description font size now is 0.9em
.issues-container .issue-card-description code font size now is 0.9em 
.projects-container .projects-description font size now is 1em
.projects-container .projects-description-text font size is 0.8em
.projects-container .projects-tile-tag font size is 0.8em
small {
  font-size: 80%; } which is well over 12px 
Therefore i think @alexdor the issue is stale and can be closed

**Comment by alexdor** [comment]
you are right @tabshaikh , thanks : )
