### ISSUE TITLE
Documentation: create the about page

### ISSUE THREAD

**Issue by bacharakis** [ossn/fixme#29]
Add information into the about page

- What does the platform does.
- Why do you need the platform
- How to use the platform

**Comment by LucyeoH** [comment]
What does this platform do? 

This platform helps contributors find open source projects that are a good fit for their skills and abilities, so that they can start contributing to open source. All of these projects have been vetted to ensure that they’re active, healthy, and ready for beginner contributions. 

Why do you need the platform? 

Our research found that while many people are interested in contributing to open source, one of the biggest barriers to getting started was difficulty in finding an appropriate project that was a match for their skills, and abilities. This platform acts as a filtering system to help people overcome that initial obstacle and find a project that is right for them. 

How to use the platform: 

On the home page describe the programming languages you're comfortable using, once you put in a language, the site will ask you more about what kinds of issues you're looking for. It will then search the projects and surface issues that match your criteria. Give it a try!

**Comment by swetax** [comment]
@bacharakis Can you please assign this to me?

**Comment by alexdor** [comment]
@swetax this issue can't be assigned to you because you aren't part of the GitHub org, but you can work freely on this issue : )

**Comment by Cassiopeia19** [comment]
@Alexandros Dorodoulis Would you unassign me please?  Or, walk me thru how
to unassign myself? Thx

**Comment by Muljayan** [comment]
@bacharakis could you review if #66  is fine
