### ISSUE TITLE
prevent showing 'closed issues' in the issues section.

### ISSUE THREAD

**Issue by makkBit** [ossn/fixme#93]
User selects technology, level of difficulty, issue type and gets list of issues.
Upon clicking on a particular issue, finds its already resolved and closed. :(
So it would be better to show only current open issues.

**Comment by alexdor** [comment]
Hi @makkBit, thanks for opening this issue. Unfortunately the status of issues on fixme's website might be running a few hours behind GitHub. The reason is that we have to request the data from GitHub's api which allows only limited amount of requests per hour. 

We could decrease the time that it takes to close a stale issues by improving the backend worker. There is already an issue open at ossn/fixme_backend#6 so we could track the progress of this there : )
